// <auto-generated />
namespace MisFinanzas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddIdGrupoGasto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIdGrupoGasto));
        
        string IMigrationMetadata.Id
        {
            get { return "201708121453457_[-AddIdGrupoGasto]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
